arm: Kconfig: Add select GENERIC_IRQ_MIGRATION for HOTPLUG_CPU
Undefined reference to 'irq_migrate_all_off_this_cpu' error happened
when build arm 32bit. So add missing select GENERIC_IRQ_MIGRATION for
arm HOTPLUG_CPU.

Change-Id: I27810f8c7d561cad3fed0f65d3c6036525d6590d
Signed-off-by: Maria Yu <aiquny@codeaurora.org>